In [1]:
import numpy as np
import pandas as pd

data  = pd.read_csv("play_tennis.csv")
data.head(5)

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [2]:
data.drop(columns=['day'],inplace=True)

In [3]:
data

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [4]:
#   Problem 1
# outlook = Sunny,Temp=Hot ,Humidity=High and wind = weak
# Play or No Play ?

In [ ]:
# Solution
# P(Yes/Sunny,Hot,High,Weak)=P(Sunny/Yes)*P(Hot/Yes)*P(High/Yes)*P(Weak/Yes)*P(Yes)
#  P(No/Sunny,Hot,High,Weak)=P(Sunny/No)*P(Hot/No)*P(High/No)*P(Weak/No)*P(No)
# compare and decide using the Maximum a Posterior rule

In [7]:
# Problem 2
# outlook = Overcast,Temp=Cold ,Humidity=Low and Wind = weak
# Play or No Play ?

In [ ]:
# Solution
# P(Yes/Overcast,Cold,Low,Weak)=P(Overcast/Yes)*P(Cold/Yes)*P(Low/Yes)*P(Weak/Yes)*P(Yes)
#  P(No/Overcast,Cold,Low,Weak)=P(Overcast/No)*P(Cold/No)*P(Low/No)*P(Weak/No)*P(No)
# compare and decide using the Maximum a Posterior rule

In [8]:
# Training
# Lookup Table(Dictionary)

# Testing

In [9]:
# p(yes)
#p(no)

In [10]:
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [11]:
p_yes = 9/14
p_no = 5/14

print(p_yes)
print(p_no)

0.6428571428571429
0.35714285714285715

In [12]:
# Outlook
pd.crosstab(data['outlook'],data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [13]:
p_overcast_no = 0
p_rain_no=2/9
p_sunny_no=3/9

p_overcast_yes = 4/9
p_rain_yes=3/9
p_sunny_yes=2/9

In [14]:
#temp
pd.crosstab(data['temp'],data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [15]:
p_cool_no = 1/5
p_hot_no=2/5
p_mild_no=2/5

p_cool_yes = 3/9
p_hot_yes=2/9
p_mild_yes=4/9

In [16]:
# Humidity

pd.crosstab(data['humidity'],data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [17]:
p_high_no = 4/5
p_normal_no = 4/5

p_high_yes = 3/9
p_normal_yes = 6/9

In [18]:
# Wind

pd.crosstab(data['wind'],data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [19]:
p_strong_no = 3/5
p_weak_no = 2/5

p_strong_yes = 3/9
p_weak_yes = 6/9

In [23]:
# outlook = Sunny,Temp=Hot ,Humidity=High and wind = weak
# P(Yes/Sunny,Hot,High,Weak)=P(Sunny/Yes)*P(Hot/Yes)*P(High/Yes)*P(Weak/Yes)*P(Yes)

# for Yes
pyes = p_sunny_yes*p_hot_yes*p_high_yes*p_weak_yes*p_yes
print(pyes)

#  P(No/Sunny,Hot,High,Weak)=P(Sunny/No)*P(Hot/No)*P(High/No)*P(Weak/No)*P(No)
# for No
pno = p_no*p_sunny_no*p_hot_no*p_high_no*p_weak_no
print(pno)

0.007054673721340387
0.01523809523809524

In [24]:
# As compare to probability of yes to no, p_no is greater than p_yes,so we conclude that there is NO PLAY